### ISSUE TITLE
Bot goes to sleep on idle

### ISSUE THREAD

**Issue by TotallyNotSethP** [dnhess/pbbot#19]
I've noticed that when you use a playbot command after the bot's been idle for a while, it will fail. I believe the hosting service you're using is doing this to save computer resources. You should consider using something like https://uptimerobot.com/ to have 100% uptime

**Comment by TotallyNotSethP** [comment]
Bump

**Comment by dnhess** [comment]
Yeah, I also noticed that, but running the command again typically works, so I haven't thought about it too much :). The service you linked looks like a monitoring service that will alert you if something goes down. I think it could help, just by the fact it can ping an API endpoint to keep the service alive, but I would like to see if a native solution could be implemented first, to avoid any external third party servies. I think creating a cron job that runs every 5 minutes or so would keep the server up, or using something like https://www.serverless.com/plugins/serverless-plugin-warmup might also work. 

This is something to consider as a quality-of-life improvement for Playbot. Thanks for reporting!

**Comment by dnhess** [comment]
I am going to close this. I'm working on a [Playbotv2](https://github.com/dnhess/playbot) that will address this issue.
